http:
  port:
  cors_allow_origins:

docker:
  image_prefix: sc
  runner_timeout: 15m

logging:
  level: debug

postgres:
  uri:

storage:
  base_path: "/var/app/uploads"

jwt:
  secret:
  access_ttl: 24h
